### PR TITLE
View changes for Advising Drop-ins

### PR DESCRIPTION
**Pull request by emmalynfoster**

### CODE REVIEW

**Review by nathankelete — COMMENTED** [review]
LGTM!

**Comment by emmalynfoster** [comment]
I need to update the comments but could you also look at the user table rq and see if we need to add a relationship in there for this. I believe we did last year but they don't for event registrations, so that confuses me on why they left that out. The structures are very similar

**Comment by nathankelete** [comment]
Just took a look and I saw that news posts have an addition in the user table, but the higher level logic of registering for an event is the same as registering for an advising appointment, especially because it's not like it's "filling up a spot" of the advisor's meeting, so i don't think we need to. office hour tickets don't have a relationship in the user table itself right?

**Comment by emmalynfoster** [comment]
True, looks good then! I'll close this

**Pull request closed without merging**
